version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app/worker
    ports:
        - 8081:5000
    volumes:
      - ${CODE_ROOT}:/app/worker
